# Generated by Django 3.0.6 on 2020-08-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200814_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Driver'),
        ),
        migrations.AlterField(
            model_name='category',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
