# Generated by Django 3.0.6 on 2020-10-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201025_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
