# Generated by Django 3.0.6 on 2020-06-21 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200511_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('active', models.BooleanField(default=False, help_text='Designates whether product is available for purchase')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Designates currency, 3 letter code, lowercase', max_length=3)),
                ('type', models.CharField(help_text='Designates whether payment is recurring or one_time', max_length=50)),
                ('interval', models.CharField(help_text='Designates billing frequency. Can be day, week, month or year', max_length=20)),
                ('unit_amount', models.IntegerField(help_text='Designates payment amount in cents')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
            options={
                'verbose_name': 'Price',
            },
        ),
    ]
