# Generated by Django 3.0.6 on 2020-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201025_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        
    ]
