# Generated by Django 3.0.6 on 2020-12-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201125_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image_url_1',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='image_url_3',
        ),
    ]
