# Generated by Django 3.0.6 on 2020-08-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200815_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Driver'),
        ),
    ]
