# Generated by Django 3.0.6 on 2020-09-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200820_1613'),
    ]

    operations = [
      
        migrations.RenameField(
            model_name='article',
            old_name='picture',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.RemoveField(
            model_name='video',
            name='driver',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='tier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='longdescription',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
