# Generated by Django 3.0.6 on 2020-09-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
        ('core', '0005_auto_20200901_1927'),
    ]

    operations = [
    ]
