# Generated by Django 3.0.6 on 2021-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='document',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='longdescription',
            field=models.TextField(max_length=9000, null=True),
        ),
    ]
