# Generated by Django 3.0.6 on 2020-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20200903_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
      
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='core.Tag'),
        ),
    ]
