# Generated by Django 3.0.6 on 2020-07-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200724_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='interval',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
