# Generated by Django 3.0.6 on 2021-03-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210301_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='document',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
