# Generated by Django 3.0.6 on 2020-09-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200921_1411'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='plan',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='charge',
            name='fee_currency',
            field=models.CharField(blank=True, default='aud', max_length=10, null=True),
        ),
    ]
