# Generated by Django 3.0.6 on 2020-09-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200921_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
