# Generated by Django 3.0.6 on 2020-10-03 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200929_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=191)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(default='aud', max_length=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plan')),
            ],
        ),
        
    ]
