# Generated by Django 3.0.6 on 2020-10-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201003_1630'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
