# Generated by Django 3.0.6 on 2020-10-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201010_2052'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='trailer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
