# Generated by Django 3.0.6 on 2020-10-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201010_2057'),
    ]

    operations = [
      
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
