# Generated by Django 3.0.6 on 2021-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shopifycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ShopifyCategory',
        ),
    ]
