# Generated by Django 3.0.6 on 2020-10-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201011_1433'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='category',
            name='trailer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
