# Generated by Django 3.0.6 on 2020-10-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201011_1703'),
    ]

    operations = [
       
    ]
