# Generated by Django 3.0.6 on 2021-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='longdescription',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
