# Generated by Django 3.0.6 on 2020-10-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201024_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
