# Generated by Django 3.0.6 on 2020-10-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

   
    operations = [
        migrations.AlterField(
            model_name='video',
            name='image_file',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
