# Generated by Django 3.0.6 on 2021-09-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210821_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video_high_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_low_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
