# Generated by Django 3.2.7 on 2021-10-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210912_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('category', models.IntegerField(default=0)),
                ('longdescription', models.TextField(max_length=9000, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('podcast_link', models.CharField(max_length=500, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('listens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
    ]
