# Generated by Django 3.0.6 on 2021-10-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='document',
        ),
    ]
