# Generated by Django 3.2.7 on 2021-10-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20211002_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='podcast_link',
            new_name='video_high_url',
        ),
    ]
