# Generated by Django 3.0.6 on 2021-10-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_podcast_link_podcast_video_high_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='release_order',
            field=models.IntegerField(default=1),
        ),
    ]
