# Generated by Django 3.2.7 on 2021-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_podcast_link_podcast_video_high_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('document', models.CharField(max_length=500, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='worksheet_category', to='core.Category')),
            ],
            options={
                'verbose_name': 'Worksheet',
                'verbose_name_plural': 'Worksheet',
            },
        ),
    ]
