# Generated by Django 3.0.6 on 2021-10-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_video_release_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='release_order',
            field=models.IntegerField(null=True),
        ),
    ]
