# Generated by Django 3.2.7 on 2021-11-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_purchaseddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='release_id',
            field=models.IntegerField(default=0),
        ),
    ]
