# Generated by Django 3.2.8 on 2021-11-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_worksheet'),
        ('core', '0026_auto_20211009_1230'),
    ]

    operations = [
    ]
