# Generated by Django 3.2.7 on 2021-11-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_video_release_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
