# Generated by Django 3.0.6 on 2020-09-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200921_1411'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='videos',
            field=models.ManyToManyField(help_text='List of users favourite videos', related_name='video', to='core.Video'),
        ),
    ]
