# Generated by Django 3.0.6 on 2020-11-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='s3_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='s3_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
