# Generated by Django 3.0.6 on 2020-12-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201122_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mail_list',
            field=models.BooleanField(default=False, help_text='Designates whether user has signed up to mailing list'),
        ),
    ]
