# Generated by Django 3.0.6 on 2020-09-27 07:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='videos',
        ),
        migrations.AddField(
            model_name='customuser',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, null=True, size=None),
        ),
    ]
