# Generated by Django 3.0.6 on 2020-10-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200927_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fname',
            field=models.CharField(default='', max_length=80, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lname',
            field=models.CharField(default='', max_length=80, verbose_name='last name'),
        ),
    ]
