# Generated by Django 3.0.6 on 2021-06-10 08:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_temp_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='temp_cat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
