# Generated by Django 3.0.6 on 2021-06-19 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210610_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='temp_cat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
