# Generated by Django 3.0.6 on 2021-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210703_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='checkout',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
