# Generated by Django 3.0.6 on 2021-08-24 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='temp_cat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token',
        ),
    ]
