# Generated by Django 3.0.6 on 2021-08-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210824_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='checkout',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temp_cat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
