# Generated by Django 3.0.6 on 2021-09-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210824_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='popup',
            field=models.IntegerField(default=0, help_text='Designates whether user has clicked popup'),
        ),
    ]
