# Generated by Django 3.2.7 on 2021-10-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='popupMyChron',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
