# Generated by Django 3.2.7 on 2021-11-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_popupmychron'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='purchasedChampions',
            field=models.DateTimeField(null=True),
        ),
    ]
