# Generated by Django 3.2.8 on 2022-02-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_purchasedchampions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lname',
            new_name='last_name',
        ),
    ]
