# Generated by Django 3.0.6 on 2020-07-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200630_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_token',
            field=models.CharField(blank=True, help_text='Stripe pay token', max_length=300, null=True),
        ),
    ]
