# Generated by Django 3.0.6 on 2020-07-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200714_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uuid',
        ),
    ]
